services:
  backend:
    container_name: cvc-backend
    build: ./backend
    ports:
      - 8001:80
    env_file:
      - .env
    networks:
      - cvc-network



networks:
  cvc-network:
    driver: bridge