services:
  backend:
    build: ./backend
    env_file:
      - .env
    networks:
      - app-network2
  
  frontend:
    build: ./frontend
    ports:
      - "3030:3030"
    env_file:
      - .env
    networks:
      - app-network2


networks:
  app-network2:
    driver: bridge