services:
  backend:
    container_name: cvc-backend
    build: ./backend
    env_file:
      - .env
    networks:
      - app-network2
  
  frontend:
    container_name: cvc-frontend
    build: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - app-network2
    restart: always


networks:
  app-network2:
    driver: bridge