services:
  backend:
    container_name: cvc-backend
    build: ./backend
    ports:
      - 8001:8001
    env_file:
      - .env
    networks:
      - cvc-network

  discord:
    container_name: cvc-discord
    build: ./discordbot
    env_file:
      - .env
    networks:
      - cvc-network

  web:
    container_name: cvc-web
    build:
    context: ./web  # Assuming your Nuxt.js app is in a 'website' directory
    dockerfile: Dockerfile  # Explicitly specify the Dockerfile name
    ports:
    - "8000:80"  # Map host port 8000 to container port 80
    networks:
    - cvc-network

networks:
  cvc-network:
    driver: bridge