# docker-compose.yml

services:
  #backend:
    #container_name: cvc-backend
    #build: ./backend
    #ports:
      #- 8001:8001
    #env_file:
      #- .env
    #networks:
      #- cvc-network
      #- vps
    #depends_on:
      #- mongodb

  #discord:
    #container_name: cvc-discord
    #build: ./discordbot
    #env_file:
      #- .env
    #networks:
      #- cvc-network
      #- vps
    #depends_on:
      #- mongodb

  #web:
    #container_name: cvc-web
    #build: ./web
    #ports:
      #- "8000:3000"
    #networks:
      #- cvc-network
      #- vps


  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db 
    networks:
      - traefik-shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db.rule=Host('db.ironfoundry.cc')"
      - "traefik.http.routers.db.entrypoints=websecure"
      - "traefik.http.routers.db.tls.certresolver=cloudflare"
      - "traefik.http.services.db.loadbalancer.server.port=27017"

networks:
  traefik-shared:
    external: true

volumes:
  mongodb_data:
    driver: local