# docker-compose.yml

services:
  backend:
    container_name: cvc-backend
    build: ./backend
    ports:
      - 8001:8001
    env_file:
      - .env
    networks:
      - cvc-network
      - vps
    depends_on: # Add dependency on mongodb
      - mongodb

  discord:
    container_name: cvc-discord
    build: ./discordbot
    env_file:
      - .env
    networks:
      - cvc-network
      - vps
    depends_on:
      - mongodb

  web:
    container_name: cvc-web
    build: ./web
    ports:
      - "8000:3000"
    networks:
      - cvc-network
      - vps


  mongodb:
    image: mongo:latest
    container_name: cvc-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db 
    networks:
      - cvc-network
      - vps

networks:
  cvc-network:
    driver: bridge
  vps:
    name: vps
    driver: bridge
    external: true

volumes:
  mongodb_data:
    driver: local