services:
  backend:
    container_name: cvc-backend
    build: ./backend
    ports:
      - 8001:8001
    env_file:
      - .env
    networks:
      - cvc-network
      - vps

  discord:
    container_name: cvc-discord
    build: ./discordbot
    env_file:
      - .env
    networks:
      - cvc-network
      - vps

  web:
    container_name: cvc-web
    build: ./web
    ports:
    - "8000:80"
    networks:
    - cvc-network
    - vps

networks:
  cvc-network:
    driver: bridge
  vps:
    name: vps
    driver: bridge
    external: true
